select * from CUSTOMER;

select * from ADDRESS;

select FIRST_NAME,LAST_NAME,ADDRESS,PHONE
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID =ADDRESS.ADDRESS_ID;

select FIRST_NAME,LAST_NAME,c.ADDRESS_ID, ADDRESS,PHONE
from CUSTOMER c left join ADDRESS a
on c.ADDRESS_ID =a.ADDRESS_ID;

select FIRST_NAME,LAST_NAME,c.ADDRESS_ID, a.ADDRESS_ID,ADDRESS,PHONE
from CUSTOMER c right join ADDRESS a
on c.ADDRESS_ID =a.ADDRESS_ID;

select FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
from EMPLOYEES E left join DEPARTMENTS d
on e.DEPARTMENT_ID = D.DEPARTMENT_ID;